name: shop_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 4.0.4
  intl: 0.16.1
  http: 0.12.0+4

  cupertino_icons: ^0.1.2
  keyboard_avoider: ^0.1.2
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
      - assets/product_placeholder.png

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
